services:
  quickjs-builder:
    image: javiermk/vidra-quickjs:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/app/dist
      - ./config.sh:/app/config.sh:ro
      - ./compile.sh:/app/compile.sh:ro
    working_dir: /app
    entrypoint: ["/app/compile.sh"]