services:
  quickjs-builder:
    build:
      context: .
    image: javiermk/vidra-quickjs:latest
    volumes:
      - ./dist:/dist
      - ./config.sh:/config.sh:ro
      - ./compile.sh:/compile.sh:ro
    entrypoint: ["/compile.sh"]
